#!/bin/bash
commits=$(git rev-list --all --count)
number=175
if [ $commits -eq 0 ]
then
    echo "No Commits Yet"
    exit 1
fi
dir="./.rgpt"
branch=$(git rev-parse --abbrev-ref HEAD)
hash=$(git rev-parse origin/$branch)
files=$(git diff --name-only $hash)

setup() {
    if [ -d $dir ]
    then
        rm -r $dir
    fi
    mkdir $dir
}
parse_file() {
    ((number++))
    loc="$dir/output-$number-$(basename ${1}).txt"
    git show $hash:$1 > $loc
    text=$(IFS= read -r -d '' text < $loc; printf '%s\n' "${text//$'\n'/\\n}")
    echo $text > $loc
}
setup
while IFS= read -r line
do
    parse_file $line
done < <(printf '%s\n' "$files")


